[package]
name = "newpfd"
version = "0.4.0"
edition = "2021"
license = " GPL-3.0-or-later"
description = "NewPFD integer compression/decompression"
homepage = "https://github.com/redst4r/newpfd-rs"
repository = "https://github.com/redst4r/newpfd-rs"
keywords = ["integer-compression", "NewPFD", "PForDelta", "encoding", "fibonacci"]
categories = ["Compression", "Algorithms"]
readme = "README.md"
include = ["/src", "README.md"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec="1"
itertools="0.11"
fibonacci_codec="0.2"
bit-vec="0.6"  # TODO: remove this old depenency
rand = "0.8"
num = "0.4"

[dev-dependencies]
criterion = "0.5"

# [[bench]]
# name = "my_benchmark"
# harness = false