[package]
name = "newpfd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec="1"
itertools="0.10.5"
fibonacci_codec="0.2"
bit-vec="0.6"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "my_benchmark"
harness = false